services:
  yamleditor:
    build: .
    container_name: yamleditor
    ports:
      - "8080:80"
    volumes:
      # Persistente Daten f√ºr Dateien
      - ${FILES_HOST_DIR:-./data/files}:/var/www/data/files
      # Datenbank als Docker Volume
      - yamleditor_db:/var/www/database
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Europe/Vienna
      - APACHE_RUN_USER=#${PUID:-33}
      - APACHE_RUN_GROUP=#${PGID:-33}

volumes:
  yamleditor_db:
